name: 'PR Metadata Action'
description: 'Adds pull request file changes as a comment to a newly opened PR'
inputs:
  owner:
    description: 'The owner of the repository'
    required: true
  repo:
    description: 'The name of the repository'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: false
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node18.8.0'
  main: 'dist/index.js'