name: 'notify-UI'
author: 'nempey@eventpower.com'
description: 'If major UI changes notify frontend team'
inputs:
  changed-files:  # id of input
    description: 'files that changed since last commit'
    required: true
    default: 'No Changes'
  emails:
    description: 'string of emails to send notification'
    required: true
    default: '0'
outputs:
  if-notified: # id of output
    description: 'bool, true if notify team'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'compass'
  color: 'green'
