name: 'PR Metadata Action'
description: 'Adds pull request file changes as a comment to a newly opened PR'
inputs:
  files:
    description: 'The files changed'
    required: true
  token:
    description: 'User token'
    required: true
outputs:
  big_change:
    description: 'Bool to indicate big UI change'
runs:
  using: 'node16'
  main: 'index.js'